{{/*
  This secret is created when the user explicitly sets gypsum.secretKey
  and does not reference an existing secret.
*/}}
{{- if and .Values.gypsum.secretKey (not .Values.gypsum.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gypsum.fullname" . }}
  labels:
    {{- include "gypsum.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.gypsum.secretKey | b64enc | quote }}
{{- end }}
